#!/usr/bin/env ruby
exit if ARGV.size == 0 or !File.exists?(ARGV[0])
input = File.read(ARGV[0])

(1..input.to_i).each do |integer|
  by3, by5 = (integer % 3 == 0), (integer % 5 == 0)
  if by3 and by5
    puts 'Hop'
  elsif by3
    puts 'Hoppity'
  elsif by5
    puts 'Hophop'
  end
end